# https://unix.stackexchange.com/a/30576 :
#bind-key @ choose-window 'join-pane -h -s "%%"'
bind-key @ choose-window 'kill-pane ; join-pane -hs %%'
# (see also https://superuser.com/a/470657 :)
# bind < split-window -h \; choose-window 'kill-pane ; join-pane -hs %%'

set -g default-terminal "tmux-256color"
set -s escape-time 0

# https://github.com/airblade/vim-gitgutter/tree/512e2999ed7ff367580e0d6bc4d2daa81663221f#when-signs-dont-update-after-focusing-vim :
set -g focus-events on

# From https://github.com/anomalyco/opencode/issues/9836#issuecomment-4090191150 or https://blog.fsck.com/releases/2026/02/26/terminal-keyboard-protocol/
#
# (Not sure this actually does the trick, though.)
set -s extended-keys always
set -as terminal-features ',xterm-kitty:extkeys'
set -s extended-keys-format csi-u
