#!/bin/bash

set -o errexit -o errtrace -o nounset -o pipefail
IFS=$'\n\t'
trap "echo 'Interrupted. Aborting with error exit status.'; exit 1;" INT
# shellcheck disable=SC2154 # (seems to parse this poorly):
trap 'err="$?"; echo "Error occured in subcommand @ ${BASH_SOURCE[0]}:$LINENO."; exit $err;' ERR

basedir="$(dirname "$0")"


declare -A pids
pids["awesome_dev"]="$( [ ! -r "$basedir/.pids/awesome_dev.pid" ] || cat "$basedir/.pids/awesome_dev.pid")"
pids["xephyr"]="$( [ ! -r "$basedir/.pids/xephyr.pid" ] || cat "$basedir/.pids/xephyr.pid")"

awesome_configuration_file="$HOME/.config/awesome/rc.lua"


function ensure_instance_stopped()
{ # {{{
  local instance="$1"
  if ps -p "${pids["$instance"]}" >& /dev/null; then
    stop_instance "$instance"
  fi
} # }}}
function ensure_instance_started()
{ # {{{
  local instance="$1"
  if ! ps -p "${pids["$instance"]}" >& /dev/null; then
    start_instance "$instance"
  fi
} # }}}
function stop_instance()
{ # {{{
  local instance="$1"

  if ps -p "${pids["$1"]}" >& /dev/null; then
    kill -9 "${pids["$1"]}"
  fi
  pids["$instance"]=''
  rm -f "$basedir/.pids/$instance.pid"
} # }}}
function start_instance()
{ # {{{
  local instance="$1"
  case "$instance" in
    awesome_dev)
      DISPLAY=:1 awesome  -c "$awesome_configuration_file" &> "$basedir/.logs/$instance.log" & pid="$!"
      ;;
    xephyr)
      # https://bugs.archlinux.org/task/73274#comment204938
      unset XDG_SEAT
      Xephyr -screen 1024x768 :1 &> "$basedir/.logs/$instance.log" & pid="$!"
      sleep 2 # to allow Xephyr to start properly
      ;;
  esac
  pids["$instance"]="$pid"
  echo "$pid" > "$basedir/.pids/$instance.pid"
} # }}}
function load_xkb()
{ # {{{
  ensure_instance_started awesome_dev
  DISPLAY=:1 setxkbmap skrewz-dvorak || true
} # }}}
function load_xresources()
{ # {{{
  ensure_instance_started awesome_dev
  #DISPLAY=:1 xrdb ~/.Xresources
} # }}}

declare -A options=( \
  ['verbose']="" \
  ['start']="" \
  ['stop']="" \
  ['restart']="" \
  ['taillogs']="" \
)

while [ "0" != "$#" ]; do
  for key in "${!options[@]}"; do
    if [[ "--${key%%:}" == "$1" ]]; then
      if [[ $key =~ : ]]; then
        options["$key"]="$2"
        shift
      else
        options["$key"]="set"
      fi
      shift
      continue 2
    fi
  done
  # Manual option parsing for non-$options options:
  case "$1" in
    --help)
      echo "(no automatic parsing of \$options here, yet. These are a good starting point, though:)"
      for key in "${!options[@]}"; do
        echo "--$key: ${options[$key]##.*##}"
      done
      ;;
    *)
      echo "Unrecogized option: \"$1\". Aborting."
      exit 1
      ;;
  esac
  shift
done


if [[ -n "${options['start']}" ]]; then
  ensure_instance_started xephyr
  ensure_instance_started awesome_dev
  load_xkb
  load_xresources
elif [[ -n "${options['taillogs']}" ]]; then
  # shellcheck disable=SC2046
  tail -F $(for key in "${!pids[@]}"; do echo "$basedir/.logs/$key.log"; done)
elif [[ -n "${options['restart']}" ]]; then
  ensure_instance_stopped awesome_dev
  ensure_instance_started awesome_dev
  load_xkb
  load_xresources
elif [[ -n "${options['stop']}" ]]; then
  ensure_instance_stopped awesome_dev
  ensure_instance_stopped xephyr
fi

# vim: fdm=marker fml=1
