#!/bin/bash

sock=~/.config/mpv/socket

if [ -S /tmp/mpv.socket ]; then
  if [ --pause = "$1" ]; then
    echo '{"command": ["cycle", "pause"]}' | socat - $sock
  elif [ --play = "$1" ]; then
    echo '{"command": ["cycle", "pause"]}' | socat - $sock
  elif [ --next = "$1" ]; then
    echo '{ "command": ["playlist-next","weak"] }' | socat - $sock
  elif [ --prev = "$1" ]; then
    echo '{ "command": ["playlist-prev","weak"] }' | socat - $sock
  elif [ --forward = "$1" ]; then
    echo '{ "command": ["seek",10,"relative"] }' | socat - $sock
  elif [ --rewind = "$1" ]; then
    echo '{ "command": ["seek",-10,"relative"] }' | socat - $sock
  fi
fi
