#!/bin/bash

if [ "$1" = "--low" ]; then
  echo -n '10' | sudo -n /usr/bin/tee /sys/class/backlight/intel_backlight/brightness >/dev/null
elif [ "$1" = "--middle" ] || [ "$1" = "--mid" ]; then
  echo -n '200' | sudo -n /usr/bin/tee /sys/class/backlight/intel_backlight/brightness >/dev/null
elif [ "$1" = "--high" ]; then
  echo -n '1023' | sudo -n /usr/bin/tee /sys/class/backlight/intel_backlight/brightness >/dev/null
else
  echo "Neither --low nor --high specified."
  exit 1
fi
