#!/bin/bash

function attempt ()
{
  for((i=0;i<10;i++)); do "$@" && return 0; done
  return 1
}

function set_external_brightness ()
{
  # Ensuring that it's the correct property that's being set:
  if attempt ddcutil getvcp 10 | grep -q Brightness; then
    attempt ddcutil setvcp 10 "$1" &
  fi
}

# Inspired by: https://unix.stackexchange.com/a/447575

if ! grep -q ^i2c.dev /proc/modules; then
  echo "No i2c-dev loaded in kernel; unlikely to work!"
fi

if [ "$1" = "--low" ]; then
  set_external_brightness 1
  echo -n '10' | sudo -n /usr/bin/tee /sys/class/backlight/intel_backlight/brightness >/dev/null
elif [ "$1" = "--middle" ] || [ "$1" = "--mid" ]; then
  set_external_brightness 10
  echo -n '200' | sudo -n /usr/bin/tee /sys/class/backlight/intel_backlight/brightness >/dev/null
elif [ "$1" = "--high" ]; then
  set_external_brightness 100
  echo -n '1023' | sudo -n /usr/bin/tee /sys/class/backlight/intel_backlight/brightness >/dev/null
else
  echo "Neither --low, --mid nor --high specified."
  exit 1
fi
