#!/usr/bin/env bash

import /tmp/screenshot.png || exit 1

screenshot_name="$(zenity --forms --add-entry "screenshot name" | sed 's/[^a-zA-Z0-9-]/_/g')"

if [ -z "$screenshot_name" ]; then
  notify-send -u critical "Not captured" "Aborting on empty file name"
  exit 1
fi

mv /tmp/screenshot.png "$HOME/screendumps/$(date +%F)_$screenshot_name.png"

notify-send "Captured" "$HOME/screendumps/$(date +%F)_$screenshot_name.png now exists"
