#!/bin/bash

if xrandr | grep -q 'DP-1-8 connected' && xrandr | grep -q 'DP-1-1 connected'; then
  xrandr --output DP-1-1  --mode 2560x1440 --pos 0x0             --rotate left \
         --output DP-1-8  --mode 2560x1440 --pos 1440x0          --rotate right \
         --output eDP-1   --mode 1920x1080 --pos $((1440*2))x0   --rotate normal
else
  xrandr --output DP-1-1  --off \
         --output DP-1-8  --off \
         --output eDP-1   --mode 1920x1080 --pos 0x0   --rotate normal
fi

feh --bg-fill persistent/black-and-white-lights-abstract-curves.jpg
#xrandr --output eDP-1   --mode 1920x1080 --right-of DP-3
