#!/usr/bin/env bash

if [ ! -x ~/repos/independent-scripts/automatic_webcam_pic/take_video_and_announce.sh ]; then
  notify-send -u critical "Not found" "You need ~/repos/independent-scripts/automatic_webcam_pic/take_video_and_announce.sh to exist."
else
  ~/repos/independent-scripts/automatic_webcam_pic/take_video_and_announce.sh --manual --capture-screenshot
fi
