#!/bin/bash

function get_output_for_edid_line ()
{
    xrandroutput="$(cat)"
    if [ "1" != "$(echo "$xrandroutput" | grep "$1" | wc -l)" ]; then
        #echo "Not unique: $1, aborting:" >&2
        echo "$xrandroutput" | grep "$1" >&2
        exit 1
    fi
    echo "$xrandroutput" | grep -B 999 "$1" | grep "connected" | tail -1 | egrep -o "^[^ ]+"
}

xrandroutput="$(xrandr --verbose)"
declare -A display
display['pos_0_screen_0']="$(echo "$xrandroutput" | get_output_for_edid_line "00483958533230363834310a202000e4")"

display['pos_1_screen_right']="$(echo "$xrandroutput" | get_output_for_edid_line "0002410328001200000a010a2020004a")"
display['pos_1_screen_middle']="$(echo "$xrandroutput" | get_output_for_edid_line "0038561e711e010a20202020202001b2")"
display['pos_1_screen_left']="$(echo "$xrandroutput" | get_output_for_edid_line "0038561e711e010a2020202020200189")"

disconnected_but_used_displays="$(sed -nre 's/^([^ ]+) disconnected [0-9]+x[0-9]+[+][0-9]+[+][0-9]+ .*$/\1/;T;p' <<< "$xrandroutput")"


if [ -n "${display['pos_1_screen_left']:-}" ] &&
   [ -n "${display['pos_1_screen_middle']:-}" ] &&
   [ -n "${display['pos_1_screen_right']:-}" ]; then
  notify-send -u "low" -t 2000 "Considering this position 1"
  sleep 2
  xrandr --output "${display['pos_1_screen_left']:-}"   --mode 2560x1440 --pos 0x0             --rotate left \
         --output "${display['pos_1_screen_middle']:-}" --mode 2560x1440 --pos 1440x0          --rotate right \
         --output "${display['pos_1_screen_right']:-}"  --mode 1920x1080 --pos $((1440*2))x$((2560*1/3))   --rotate normal
elif [ -n "${display['pos_1_screen_right']:-}" ]; then
  xrandr --output "${display['pos_1_screen_left']:-}"   --off \
         --output "${display['pos_1_screen_middle']:-}" --off  \
         --output "${display['pos_1_screen_right']:-}"  --mode 1920x1080 --pos 0x0   --rotate normal
elif [ -n "${display['pos_0_screen_0']:-}" ]; then
  notify-send -u "low" -t 2000 "Considering this position 0"
  xrandr --output "${display['pos_0_screen_0']}" --mode 2048x1152 --pos 0x0 \
         --output LVDS-1                                   --auto --pos 224x1152   --rotate normal
else
  notify-send -u "critical" -t 10000 "No display configuration needed" "Hence, nothing configured"
fi

if [ -n "$disconnected_but_used_displays" ]; then
  cmd='xrandr '
  for display in $disconnected_but_used_displays; do
    cmd="${cmd}--output $display --off "
  done
  notify-send -u "low" -t 2000 "Will run: \`$cmd\` now..."
  sleep 2
  eval "$cmd"
fi

feh --bg-fill ~/persistent/background.png
#xrandr --output eDP-1   --mode 1920x1080 --right-of DP-3
