-- Vim color file - corporation_modified
-- Generated by http://bytefluent.com/vivify 2018-04-16
-- Converted to lua by skrewz@20240516

vim.o.background = dark

vim.g.colors_name = "skrewzscheme"

-- Apply the colors to various highlight groups
local function apply_colors()
  vim.api.nvim_set_hl(0, "Normal", {fg="#F9F9FF"})
  vim.api.nvim_set_hl(0, "IncSearch", {fg="#192224", bg="#BD9800"})
  vim.api.nvim_set_hl(0, "WildMenu", {bg="#A1A6A8", sp="#A1A6A8"})
  vim.api.nvim_set_hl(0, "SignColumn", {fg="#192224", bg="#536991", sp="#536991"})
  vim.api.nvim_set_hl(0, "SpecialComment", {fg="#BD9800", sp="NONE"})
  vim.api.nvim_set_hl(0, "Typedef", {fg="#536991", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "Title", {fg="#F9F9FF", bg="#192224", sp="#192224", bold=true})
  vim.api.nvim_set_hl(0, "Folded", {fg="#192224", bg="#A1A6A8", sp="#A1A6A8", italic=true})
  vim.api.nvim_set_hl(0, "PreCondit", {fg="#BD9800", sp="NONE"})
  vim.api.nvim_set_hl(0, "Include", {fg="#BD9800", sp="NONE"})
  vim.api.nvim_set_hl(0, "TabLineSel", {fg="#192224", bg="#BD9800", sp="#BD9800", bold=true})
  vim.api.nvim_set_hl(0, "StatusLineNC", {fg="#192224", bg="#5E6C70", sp="#5E6C70", bold=true})
  vim.api.nvim_set_hl(0, "NonText", {fg="#5E6C70", sp="NONE", italic=true})
  vim.api.nvim_set_hl(0, "DiffText", {bg="#492224", sp="#492224"})
  vim.api.nvim_set_hl(0, "ErrorMsg", {fg="#A1A6A8", bg="#912C00", sp="#912C00"})
  vim.api.nvim_set_hl(0, "Debug", {fg="#BD9800", sp="NONE"})
  vim.api.nvim_set_hl(0, "PMenuSbar", {bg="#848688", sp="#848688"})
  vim.api.nvim_set_hl(0, "Identifier", {fg="#00ff87", sp="NONE"})
  vim.api.nvim_set_hl(0, "SpecialChar", {fg="#BD9800", sp="NONE"})
  vim.api.nvim_set_hl(0, "Conditional", {fg="#BD9800", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "StorageClass", {fg="#536991", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "Todo", {fg="#F9F9FF", bg="#BD9800", sp="#BD9800"})
  vim.api.nvim_set_hl(0, "Special", {fg="#BD9800", sp="NONE"})
  vim.api.nvim_set_hl(0, "LineNr", {fg="#ffaf00", sp="NONE"})
  vim.api.nvim_set_hl(0, "StatusLine", {fg="#000000", bg="#005fff", sp="#005fff", bold=true})
  vim.api.nvim_set_hl(0, "Label", {fg="#BD9800", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "PMenuSel", {fg="#192224", bg="#BD9800", sp="#BD9800"})
  vim.api.nvim_set_hl(0, "Search", {fg="#00ff00", sp="NONE", italic=true, underline=true})
  vim.api.nvim_set_hl(0, "Delimiter", {fg="#BD9800", sp="NONE"})
  vim.api.nvim_set_hl(0, "Statement", {fg="#19bd00", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "SpellRare", {fg="#F9F9FF", bg="#192224", sp="#192224", underline=true})
  vim.api.nvim_set_hl(0, "Comment", {fg="#5E6C70", sp="NONE", italic=true})
  vim.api.nvim_set_hl(0, "Character", {fg="#A1A6A8", sp="NONE"})
  vim.api.nvim_set_hl(0, "Float", {fg="#A1A6A8", sp="NONE"})
  vim.api.nvim_set_hl(0, "Number", {fg="#A1A6A8", sp="NONE"})
  vim.api.nvim_set_hl(0, "Boolean", {fg="#A1A6A8", sp="NONE"})
  vim.api.nvim_set_hl(0, "Operator", {fg="#BD9800", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "CursorLine", {bg="#222E30", sp="#222E30"})
  vim.api.nvim_set_hl(0, "TabLineFill", {fg="#192224", bg="#5E6C70", sp="#5E6C70", bold=true})
  vim.api.nvim_set_hl(0, "WarningMsg", {fg="#A1A6A8", bg="#912C00", sp="#912C00"})
  vim.api.nvim_set_hl(0, "VisualNOS", {fg="#192224", bg="#F9F9FF", sp="#F9F9FF", underline=true})
  vim.api.nvim_set_hl(0, "DiffDelete", {bg="#192224", sp="#192224"})
  vim.api.nvim_set_hl(0, "ModeMsg", {fg="#F9F9F9", bg="#192224", sp="#192224", bold=true})
  vim.api.nvim_set_hl(0, "CursorColumn", {bg="#222E30"})
  vim.api.nvim_set_hl(0, "Define", {fg="#BD9800", sp="NONE"})
  vim.api.nvim_set_hl(0, "Function", {fg="#0000d7", sp="NONE", bold=true, underline=true})
  vim.api.nvim_set_hl(0, "FoldColumn", {fg="#192224", bg="#A1A6A8", sp="#A1A6A8", italic=true})
  vim.api.nvim_set_hl(0, "PreProc", {fg="#BD9800", sp="NONE"})
  vim.api.nvim_set_hl(0, "Visual", {fg="#192224", bg="#F9F9FF", sp="#F9F9FF"})
  vim.api.nvim_set_hl(0, "MoreMsg", {fg="#BD9800", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "SpellCap", {fg="#F9F9FF", bg="#192224", sp="#192224", underline=true})
  vim.api.nvim_set_hl(0, "VertSplit", {fg="#192224", bg="#5E6C70", sp="#5E6C70", bold=true})
  vim.api.nvim_set_hl(0, "Exception", {fg="#BD9800", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "Keyword", {fg="#0010bd", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "Type", {fg="#536991", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "DiffChange", {bg="#492224", sp="#492224"})
  vim.api.nvim_set_hl(0, "Cursor", {fg="#192224", bg="#F9F9F9", sp="#F9F9F9"})
  vim.api.nvim_set_hl(0, "SpellLocal", {fg="#F9F9FF", bg="#192224", sp="#192224", underline=true})
  vim.api.nvim_set_hl(0, "Error", {fg="#A1A6A8", bg="#912C00", sp="#912C00"})
  vim.api.nvim_set_hl(0, "PMenu", {fg="#192224", bg="#5E6C70", sp="#5E6C70"})
  vim.api.nvim_set_hl(0, "SpecialKey", {fg="#5E6C70", sp="NONE", italic=true})
  vim.api.nvim_set_hl(0, "Constant", {fg="#A1A6A8", sp="NONE"})
  vim.api.nvim_set_hl(0, "Tag", {fg="#BD9800", sp="NONE"})
  vim.api.nvim_set_hl(0, "String", {fg="#A1A6A8", sp="NONE"})
  vim.api.nvim_set_hl(0, "PMenuThumb", {bg="#a4a6a8", sp="#a4a6a8"})
  vim.api.nvim_set_hl(0, "MatchParen", {fg="#BD9800", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "Repeat", {fg="#BD9800", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "SpellBad", {fg="#F9F9FF", bg="#192224", sp="#192224", underline=true})
  vim.api.nvim_set_hl(0, "Directory", {fg="#536991", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "Structure", {fg="#536991", sp="NONE", bold=true})
  vim.api.nvim_set_hl(0, "Macro", {fg="#BD9800", sp="NONE"})
  vim.api.nvim_set_hl(0, "Underlined", {fg="#F9F9FF", bg="#192224", sp="#192224", underline=true})
  vim.api.nvim_set_hl(0, "DiffAdd", {bg="#193224", sp="#193224"})
  vim.api.nvim_set_hl(0, "TabLine", {fg="#192224", bg="#5E6C70", sp="#5E6C70", bold=true})
  vim.api.nvim_set_hl(0, "cursorim", {fg="#192224", bg="#536991", sp="#536991"})
end

-- Finally, apply the colors
--apply_colors()



return {
   load = load,
   setup = setup,
   configs = get_configs,
   colors = function() return get_configs().colors end,
}
